### ISSUE TITLE
Shift-Scroll is still changing volume for 5% when "Hide from Alt-Tab" is enabled

### ISSUE THREAD

**Issue by MiincK** [anonymousthing/ListenMoeClient#10]
Ctrl-Scroll and Alt-Scroll to change visualiser settings also don't work with "Hide from Alt-Tab"

**Comment by bitnimble** [comment]
Is this only an issue with the most recent release?
What keyboard are you using, and what version of Windows are you on?

Thanks.

**Comment by MiincK** [comment]
Windows 10. Issue was from 1.2.10 (or earlier, that was my first ver)

**Comment by bitnimble** [comment]
Fixed. Thanks for the report. I didn't make a new release since it was just a small fix, I've just updated release 1.2.14 so just redownload it from the [releases page](https://github.com/anonymousthing/ListenMoeClient/releases/latest) to get the new version.
