### ISSUE TITLE
Graphical glitch in Windows Audio Mixer

### ISSUE THREAD

**Issue by NotAkitake** [anonymousthing/ListenMoeClient#12]
![t8gwvlp](https://user-images.githubusercontent.com/7873528/30653469-70a3a7e6-9e2b-11e7-9f21-74f64b4511fd.jpg)

This happens.
OS: Windows 10 Family Edition version 10.0.15063 x64 bits.

**Comment by robflop** [comment]
I've just checked and I can confirm also experiencing this issue on the same OS.

**Comment by Pitu** [comment]
Can confirm as well on Windows 10 Pro 10.0.15063 x64.
https://lolisafe.moe/ZrQ03kwM.png

**Comment by bitnimble** [comment]
Fixed. Will be released in the next update.
