### ISSUE TITLE
Process remaining opened when closing the application at times

### ISSUE THREAD

**Issue by NotAkitake** [anonymousthing/ListenMoeClient#13]
Title says it all.

Sometimes when closing the application using the cross on it, the .exe remains open in the process list of windows.

**Comment by robflop** [comment]
Just to make sure, you are not using the close-to-tray option, correct?

(Though this would be obvious as the music would continue playing etc...)

**Comment by NotAkitake** [comment]
![f8ckdlw](https://user-images.githubusercontent.com/7873528/30662782-966fb1aa-9e48-11e7-81c9-20a5ddf22888.jpg)

It doesn't happen every single time though, it's odd.

**Comment by bitnimble** [comment]
Fixed. Will be released in the next patch.
