### ISSUE TITLE
Latest opacity release bugs

### ISSUE THREAD

**Issue by MiincK** [anonymousthing/ListenMoeClient#20]
If you change opacity to any value not 1.0, "Hide from alt-tab" option is not hiding from alt-tab, only from taskbar.
Also, if you reopen settings, only the opacity slider will show right opacity, text will say "1.0" before you change value again:
![image](https://user-images.githubusercontent.com/25132061/32988716-c96b2f52-cd1a-11e7-9ef0-13308fc7b6d4.png)
PC: Windows 10 Pro x64, v1.2.18

**Comment by bitnimble** [comment]
Thanks for the report! Fixed 😃
