### ISSUE TITLE
RawInput is not working with Hide from alt-lab (again)

### ISSUE THREAD

**Issue by MiincK** [anonymousthing/ListenMoeClient#23]
[(Shift / Ctrl / Alt) + Scroll] does the same as just the [Scroll] with Hide from Alt-tab enabled. The same bug was in LISTEN-moe/windows-app#10

OS: Windows 10 Pro x64, ver 1.3.1

**Comment by bitnimble** [comment]
I'm aware of the issue, I encountered it myself a couple hours ago - I'll be fixing this one tomorrow after I wake up. Cheers for the report again.
