### ISSUE TITLE
Pause button broken when Visualiser is disabled

### ISSUE THREAD

**Issue by HolyOlaf** [anonymousthing/ListenMoeClient#25]

**Comment by iCrawl** [comment]
That stuff isn't there for just shits and giggles btw: 
![image](https://user-images.githubusercontent.com/20760160/34329531-7c22ada0-e904-11e7-94ca-5fd8a467be93.png)

**Comment by HolyOlaf** [comment]
Sorry for not

**Comment by HolyOlaf** [comment]
Sorry for not giving that much detail, but I'm pretty sure you don't need that much.
I guess it's just a small problem in the file MainForm.cs, line 543 and 556 with TogglePlayback.

PS:
It happens on Windows 10.

**Comment by bitnimble** [comment]
Cheers, just woke up - will fix.
