### ISSUE TITLE
Favourites button doesn't work

### ISSUE THREAD

**Issue by MiincK** [anonymousthing/ListenMoeClient#27]
**Please describe the problem you are having in as much detail as possible:**
It is referencing an old api method '/api/songs/favourite', it is now replaced with '/api/favourites/{id}' (POST and DELETE). You can see my solution: MiincK@293c901

- Operating system: Win10, but it is not necessary

**Comment by bitnimble** [comment]
Thanks for the report, will push a fix soon 🙌

**Comment by bitnimble** [comment]
Fixed in 00c0ee8.
