### ISSUE TITLE
Better volume control

### ISSUE THREAD

**Issue by HolyOlaf** [anonymousthing/ListenMoeClient#29]
I think a setting that allows users to set a custom volume step would be a useful addition.

In case it is unclear what I mean by that, right now it seems that the user can only change the volume in steps of five (or of course by manually changing the value in the .ini file). 
By adding a step option the volume could be changed by a custom value, improving the control.

**Comment by robflop** [comment]
If you hold shift while scrolling you can change it by 1%.

https://i.robflop.me/drk6mVyW.webm

**Comment by HolyOlaf** [comment]
Didn't know you could do that, so thanks for the information!

But I still think it would be nice to have that option (or make the shift thing more obvious).
