### ISSUE TITLE
App cease to work until app's restart after computer resume from standby mode

### ISSUE THREAD

**Issue by Zeereen** [anonymousthing/ListenMoeClient#3]
Application either freezes and quit on its own with system error code or the audio infinitely loops 0.25-0.5 second of audio until user close the application and starts the application up again (audio track title doesn't update either when audio stuttering); only occurs upon system resuming from standby mode.

OS: Win 7 64-bit
Application version: 1.1.10 (Commit: 474b80a )

Edit: [Dec. 21, 2016]
Clarified audio bug above ^

Found out that bug only occurs if the application is still playing music as user puts the computer to sleep/standby mode. If user pause the playback of music and then put computer to sleep/standby mode then bug does not occur.

New quirk: If audio loop occurs, as stated in 1st paragraph,  one way to fix is to pause the playback and resume playback. Audio is fixed but song title don't update even after transitioning to the next song.

**Comment by bitnimble** [comment]
After moving to the new audio framework, I can no longer reproduce this bug; I will close it for now, but if it appears again then just reopen it.
