### ISSUE TITLE
Listen.moe client stays on after closing the app

### ISSUE THREAD

**Issue by Welkser** [anonymousthing/ListenMoeClient#33]
**Please describe the problem you are having in as much detail as possible:**
When I close the app it leaves Listen.moe client still running to the background. If I try to open the app again later it won't open but it will add more listen.moe clients to my taskbar. 
Listen.moe open normally
![before closing](https://user-images.githubusercontent.com/39081705/39745592-5b0e2ea8-52b0-11e8-92b8-ab063db486b3.png)
After closing the app
![after closing](https://user-images.githubusercontent.com/39081705/39745601-603a5d16-52b0-11e8-9e6b-35e197143152.png)
And when trying to restart this happens
![trying to restart](https://user-images.githubusercontent.com/39081705/39745606-64ee3a30-52b0-11e8-9835-516592b2c02d.png)

**Further details:**
- Operating system: 10 pro V:1709
- Priority this should have –  Pretty important - It uses some of pc's memory and if more of them are open it will use more

**Comment by iCrawl** [comment]
Fixed in 1.4.0
