### ISSUE TITLE
Discord Rich Presence.. Too Rich

### ISSUE THREAD

**Issue by Sphygo** [anonymousthing/ListenMoeClient#38]
Any time I have the desktop app open, discord shows what song I am listening too. That's cool, but it doesn't show up in the games tab in settings, so I can't turn it off, and it overrides any other program I have running. 

I'd like to listen in the background and show what game I'm playing, not play in stealth and show everyone what song I'm listening to. No clue if this is discord or Listen.moe that is causing it, but it's an issue nonetheless. Example in image below. Two monitors if that could somehow be causing it. GW2 doesn't show up, but instead Listen.moe does. Launching GW2 doesn't make that show up over Listen.moe, and quitting Listen.moe and then relaunching doesn't keep it away. It hogs all the Rich Presence. Second pic, it shows GW2 in settings, but not in any of my servers.
![screenshot 23](https://user-images.githubusercontent.com/33641459/42789972-e1f96528-892d-11e8-8c4d-cde092847608.png)
![screenshot 24](https://user-images.githubusercontent.com/33641459/42789973-e21058aa-892d-11e8-9064-e4478dff4be3.png)

**Comment by Adaliciously** [comment]
Only playing games that support rich presence too (like League of Legends) overwrites the listen.moe presence. 
+1 for this, however this is more like discord's problem.

**Comment by Sphygo** [comment]
I was talking to the discord group for Listen.moe and I got a workaround by disabling rich presence in the files for Listen.moe. I also sent Discord a message about it but I can't remember what they said about it. No solution through them though.
Your answer makes sense though as to why it was overpowering GW2. Thanks.
