### ISSUE TITLE
Player stuck on "Connecting..." but audio still plays

### ISSUE THREAD

**Issue by kotx** [anonymousthing/ListenMoeClient#41]
**Please describe the problem you are having in as much detail as possible:**
Visualizations and audio work but the title, author and album do not appear. "Connecting..." is shown instead. 
**Further details:**
![image](https://user-images.githubusercontent.com/33439542/78313780-c990f880-750c-11ea-8ad5-90e24d5ad495.png)
- Operating system (considering this is Windows only, just supply a number): 10 64-bit
- Priority this should have – please be realistic and elaborate if possible:
High, since this is basic functionality the player should have

**Comment by kotx** [comment]
After a song finishes playing, the player and visualizations become silent.

**Comment by Pitu** [comment]
Hi, this app has kinda been deprecated and hasn't been updated in a long while. You could give this other one a try https://github.com/LISTEN-moe/desktop-app

**Comment by ItsMeLeeson** [comment]
I fixed the issues described here in my pull request #40

**Comment by kotx** [comment]
@Pitu That's sad to hear. Really liked the systray and corner-snapping functionality. Ah well, anything in the name of cross-platform compatibility..

@ItsMeLeeson That's cool, I might check that out later. Thanks for the help!
