### ISSUE TITLE
NullPointer if stream paused before connection is established

### ISSUE THREAD

**Issue by buckley-w-david** [anonymousthing/ListenMoeClient#9]
I've found that if one presses the pause button immediately after starting the program, the error in the attached file will come up.
[error.txt](https://github.com/anonymousthing/ListenMoeClient/files/1184987/error.txt)

**Comment by bitnimble** [comment]
Cheers, fixed. I'll make a new release after a while, or once I find another bug or two (or another feature) so I can package them in the same release.
